### ISSUE TITLE
Close Structures menu button stops working after clicking System Structures

### ISSUE THREAD

**Issue by fareskalaboud** [nergmada/betweentwostars-help#2]
- Click on Structures.
- Click on Jianing Station

**Expected**
- A modal appears with some information about the structure

**Actual**
- Nothing happens

**Additional notes**
- It is no longer possible to close the Structures menu, and NONE of the other buttons or actions open or close any menus.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/4170046/154810589-36c36cdb-11c7-4865-99ae-95114a3b38ff.png">

**Comment by nergmada** [comment]
This issue has now been resolved, this was an overly zealous interpretation of how much data should be returned by the CMS regarding other players structures. For class 4 and above structures, they're considered public amenities
