### ISSUE TITLE
Overlapping menus on Deploy Probe modal

### ISSUE THREAD

**Issue by fareskalaboud** [nergmada/betweentwostars-help#4]
Menus overlap, slight readability problem ensues.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/4170046/154811257-c8112063-2c24-44fe-8c89-26764a5ffc6e.png">

**Comment by nergmada** [comment]
Issue #1 will resolve the readability issue, although ideally only one dropdown would be open at a time
