### ISSUE TITLE
On selecting Probe and Target, a RangeError is thrown

### ISSUE THREAD

**Issue by fareskalaboud** [nergmada/betweentwostars-help#5]
To reproduce:
- Click Actions
- Click Deploy Probe
- Select any probe
- Select any target
- Check console

<img width="649" alt="image" src="https://user-images.githubusercontent.com/4170046/154811338-68050bda-6fc4-4388-8b89-c5b1a73a14e2.png">

**Comment by nergmada** [comment]
Lol, gotta love some unguarded recursion. Resolved.
