### ISSUE TITLE
Ship class shown as "null"

### ISSUE THREAD

**Issue by fareskalaboud** [nergmada/betweentwostars-help#7]
Unless that's a [class of ship with respect to god of death and undeath](http://realms.dndpedia.com/index.php?title=Church_of_Null)...

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/4170046/154811374-55cf08b6-4310-4c81-a5a3-4a6a37ed8332.png">

**Comment by nergmada** [comment]
This data was missing from the CMS. It's resolved for this model, but have attached new issue #11
